/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int EOL = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int TIMES = 13;
  /** RegularExpression Id. */
  int OPEN_PAR = 14;
  /** RegularExpression Id. */
  int CLOSE_PAR = 15;
  /** RegularExpression Id. */
  int PREVIOUS = 16;
  /** RegularExpression Id. */
  int EXP = 17;
  /** RegularExpression Id. */
  int FATORIAL = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 6>",
    "<NUMBER>",
    "<DIGITS>",
    "<EOL>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "\"^\"",
    "<FATORIAL>",
  };

}
