/* Generated By:JavaCC: Do not edit this line. ConversorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConversorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int LETTERS = 9;
  /** RegularExpression Id. */
  int BASE = 10;
  /** RegularExpression Id. */
  int EOL = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 6>",
    "<NUMBER>",
    "<DIGITS>",
    "<LETTERS>",
    "<BASE>",
    "<EOL>",
  };

}
